apiVersion: v1
kind: Service
metadata:
  name: microapp-service
spec:
  selector:
    app: microapp-a
  type: ClusterIP
  ports:
  - name: root
    protocol: TCP
    port: {{ .Values.microAppA.port }}
    targetPort: {{ .Values.microAppA.port }}
